// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfop4Cm-OtoJot5gqFOoiHtrJQjwj7grU',
    appId: '1:1014331668523:web:164a10d549db856335926e',
    messagingSenderId: '1014331668523',
    projectId: 'xloop-tours-dev',
    authDomain: 'xloop-tours-dev.firebaseapp.com',
    storageBucket: 'xloop-tours-dev.firebasestorage.app',
    measurementId: 'G-HYCMCK9RT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKPulq8eAFFg7DbsiWA4nyqeTnJy_dKDw',
    appId: '1:1014331668523:android:bafbe442b4304f0935926e',
    messagingSenderId: '1014331668523',
    projectId: 'xloop-tours-dev',
    storageBucket: 'xloop-tours-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwS2Q7gQRMZ0PAfztwcXfy7WqfzdRDA_U',
    appId: '1:1014331668523:ios:9bb325c6662728a335926e',
    messagingSenderId: '1014331668523',
    projectId: 'xloop-tours-dev',
    storageBucket: 'xloop-tours-dev.firebasestorage.app',
    iosClientId: '1014331668523-51e9riafn4samfp8c213gf27ueinndi8.apps.googleusercontent.com',
    iosBundleId: 'com.example.xloopInvoice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwS2Q7gQRMZ0PAfztwcXfy7WqfzdRDA_U',
    appId: '1:1014331668523:ios:9bb325c6662728a335926e',
    messagingSenderId: '1014331668523',
    projectId: 'xloop-tours-dev',
    storageBucket: 'xloop-tours-dev.firebasestorage.app',
    iosClientId: '1014331668523-51e9riafn4samfp8c213gf27ueinndi8.apps.googleusercontent.com',
    iosBundleId: 'com.example.xloopInvoice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfop4Cm-OtoJot5gqFOoiHtrJQjwj7grU',
    appId: '1:1014331668523:web:9315df666e5810a535926e',
    messagingSenderId: '1014331668523',
    projectId: 'xloop-tours-dev',
    authDomain: 'xloop-tours-dev.firebaseapp.com',
    storageBucket: 'xloop-tours-dev.firebasestorage.app',
    measurementId: 'G-CP22YLDKMG',
  );

}